language: scala
jdk: openjdk8
script: project/travis.sh

# Build only master and version tags - http://stackoverflow.com/a/31882307/463761
branches:
  only:
    - master
    - /^v[0-9]/

env:
  global:
    - COURSIER_PROGRESS=0
    - secure: q/AN4Esfzux4LWssh8mgQWPxgXhpFYmfesujb6qsSM5jiFAHBsH7cNH8uLVWk+lbmseou1H49GK2DV19iieZYzEDzjosAdc5MmbfcWvKE+pvQ+mnP26658a2ZqXUOQ0ewOxwB/jKMnnNSwpasUcHffM0l5RbQzSZLRjR6642qtomtAaxJwg/OKyeCRwj92qpEqsUdkj200tjNGEDKKBIeMFB+o2bkMY5CG9Dt7toAgfX3Ufa1tCu617vPMhDF8h+XcWC5QdK5ksW62j4cj+ze7N7GhWyUGQfHKgXZa5BQ5jFlf4rXOtTYRp6XFS2dSXX27wr9dsGG8vrcbrAVd+MxgS0zIXw1IJZ3ACQXKY/dwfQUJyOI5aa6OevVWKcGKv42D7p/dkorJR1dGd2zZ5K1eanFaKaTKvoASyaaaZ/ixUueEQdOv6vVfsGbDjyKmxeBNNL+zgIG0nBtgr/KF03eoBUhN5G9jstcwmcKcj+jm6ARk8n/nzBS7Zi/tIO6zCAEPFslBq0IgoG197PgnwLah05QGl1CRb+RRM4K3W7X9kJdLtdhM26plrZqY49FgUYLkO6GKtmFIEB1FOe+mmTK5sw3GGwZZdRMLSACS8LhZQwa8riA419Gi+7BPWYSPpoDeHxk5ZT4cW8U5tsJlg4+nVpeAGX/AVJw6mEgMH+geQ=
    - secure: aYb2ahRmSg5hjDlxTRdEkW+gOWwhQ0Qxer402zY0tJXtWoL01dklq3BAt5EvjrWmUOrIxvkSE4HQoH3F/dir27Nlroigdp3YakvRfGwmSbwxrgpcLn5nrB5PERukw22bulhH3jsMnP8DEzys7R1EFx4z6XRvLTQHgzZIhZAuItc+7wdAuBQrDzxyjw//KmhB1eZO3afmLu7kgWdi0T1/xsulhWaOs/4WN4uIMXTPD09xyP3HfE6x6mpFK/TLdceO9DeIROHHk1Irigsvh734O5N0/hwyY3kVR/WUlLbJ6POKS5JIPrKQJdo4rqFisZMxvhtF2HyZQCMl6aB/Ev+or21kOs+uc4YP+0NCYDewmPjoUbdJZvYQKHRAcliZGAb1C0JrIczpGKSTLW/Ec6Y6BlQVPz+gKFqJTGMNXgeEqJLcfz126gBbIBeX3JnH4A+iTbMinjHmQZF3S8LRPm4J53SoxEnkrgYN73K1NJWOpBLXGWu6rRKNWNIa8WgHAlaOaocbZT1EQWj9twJyfT504WD2IhokBfqO2a67/vwMaoT9I0qrWw2XByTZDh2ZI/bJDn1kTf/hbm8sBgJ4+sdHfAh7JmqH/9W4jrBEDOHDDYQwGo6DXhBYXRybQctzgECZ3HAKgL0/HC6sb8tFCSoH12GkwOkACyhPXJfxJTenlS4=
  matrix:
    - TRAVIS_SBT_VERSION=0.13.x
    - TRAVIS_SBT_VERSION=1.x

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete

notifications:
  email:
    on_success: never
